"""T-07: deterministic fixture navigation generated from synthetic provenance."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render() -> str:
    lines = [
        "# Synthetic fixture index",
        "",
        "Generated by `python scripts/fixture_index.py`; check with `--check`.",
        "All fixtures are synthetic. Existing fixture bytes remain the test authority.",
        "",
        "Use [adapter/profile compatibility](../docs/MATRIX.md) to select a format.",
        "Use [detector/recipe coverage](../tests/MATRIX.md) to locate test node IDs.",
        "The [starter kit](../docs/STARTER_KIT.md) provides runnable examples.",
        "",
        "## Actual detector golden paths",
        "",
        "Nine legacy goldens exercise the reader and cover SL001/SL002. The rows below",
        "exercise public check_file/check_dir detection and cover all 34 codes.",
        "",
        "| Code | Execution | Input | Golden |",
        "| --- | --- | --- | --- |",
    ]
    for path in sorted((ROOT / "fixtures/conformance/detectors").glob("*.expected.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        code = path.name.split(".")[0].upper()
        source = data["input"]
        golden = path.relative_to(ROOT / "fixtures").as_posix()
        lines.append(f"| {code} | {data['mode']} | [{source}]({source}) | [golden]({golden}) |")
    lines += [
        "",
        "## Provenance inventory",
        "",
        "Counts are direct files excluding PROVENANCE.json and this index; nested folders",
        "have their own rows. Corpus labels are synthetic expectations, not real-data accuracy.",
        "",
        "| Directory | Files | Provenance |",
        "| --- | ---: | --- |",
    ]
    for path in sorted((ROOT / "fixtures").rglob("PROVENANCE.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        if data.get("contains_real_data") is not False:
            raise ValueError("Fixture provenance must explicitly exclude real data")
        relative = path.parent.relative_to(ROOT / "fixtures").as_posix()
        count = sum(
            p.is_file() and p.name not in {"PROVENANCE.json", "INDEX.md"}
            for p in path.parent.iterdir()
        )
        lines.append(
            f"| [{relative}]({relative}/) | {count} | [source]({relative}/PROVENANCE.json) |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "fixtures/INDEX.md"
    expected = render()
    if args.check:
        return 0 if target.read_text(encoding="utf-8") == expected else 1
    target.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
